name: Deploy to github

on:
  push:
    tags:
      - 'a[0-9]+.[0-9]+.[0-9]+'

## 2
jobs:
  ## 3
  build:
    runs-on: ubuntu-latest
    steps:
      # 1
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # 2

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION

      - name: Accept Android licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build
        uses: gradle/gradle-build-action@v3

      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: composeApp/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY2 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      # 4
      - name: Draft Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "app/build/outputs/apk/**/*"
          token: ${{ secrets.TOKEN }}