name: Update Dependencies

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Perform dependency resolution and write new lockfiles
        run: ./gradlew dependencies --write-locks
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report'
          body: |
              Update report
              - Updated with *today's* date
              - Auto-generated by [create-pull-request][1]
              
              [1]: https://github.com/peter-evans/create-pull-request
          labels: |
              report
              automated pr
          assignees: peter-evans
          reviewers: peter-evans
          team-reviewers: |
              developers
              qa-team
          milestone: 1
          draft: false